config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :comments, only: [:show, :create] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :votes, only: [:destroy]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  content           :text             not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord
  include Votable
  
  validates :author, :post, :content, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post

  has_many :child_comments,
    class_name: :Comment,
    foreign_key: :parent_comment_id,
    primary_key: :id

  belongs_to :parent_comment,
    class_name: :Comment,
    foreign_key: :parent_comment_id,
    primary_key: :id,
    optional: true


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      if @comment.parent_comment_id.nil?
        redirect_to post_url(@comment.post_id)
      else
        redirect_to comment_url(@comment.parent_comment_id)
      end
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment_url(@comment.post_id)
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<a class="comment"><%="#{comment.content}" %></a>
<br>
<a class "author">posted by: <%="#{comment.author.username}"%></a>
<a class="karma">(Karma: <%=comment.sum_votes%>)
  <%= link_to '<i class="fa fa-arrow-up"></i>'.html_safe, upvote_comment_url(comment), method: :post %>
  <%= link_to '<i class="fa fa-arrow-down"></i>'.html_safe, downvote_comment_url(comment), method: :post %>
<%= link_to "Show Comment", comment_url(comment) %></a>
  <% if !comments_by_parent[comment].empty? %>
    <ul>
      <% comments_by_parent[comment].each do |child| %>
      <li><%= render("comments/comment",
            comment: child,
            comments_by_parent: comments_by_parent) %></li>
      <% end %>
    </ul>
  <% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
this is a testing password_digest

<ul>
  <li>hi
    <ul>
      <li>hi</li>
    </ul>
  </ul>

app/views/comments/show.html.erb
<% if @comment.parent_comment.nil? %>
  <% header_string = @comment.post.title %>
<% else %>
  <% header_string = @comment.parent_comment.content[0..5] %>
<% end %>
<h2>Comment reply to <%=header_string%>...</h2>
<a class="comment"><%="#{@comment.content}" %></a>
<br>
<a class "author">posted by: <%="#{@comment.author.username}"%></a>
<a class="karma">(Karma: <%=@comment.sum_votes%>)
  <%= link_to '<i class="fa fa-arrow-up"></i>'.html_safe, upvote_comment_url(@comment), method: :post %>
  <%= link_to '<i class="fa fa-arrow-down"></i>'.html_safe, downvote_comment_url(@comment), method: :post %>
<form class="" action="<%=comments_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="comment[post_id]" value="<%=@comment.post_id%>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%=@comment.id%>">
  <label>Reply:
  <textarea name="comment[content]"></textarea>
  </label>
  <input type="submit" name="" value="Reply">
</form>
<br><br>
<ul>
  <% @comment.post.comments_by_parent[@comment].each do |child| %>
    <li><%= render("comments/comment",
            comment: child,
            comments_by_parent: @comment.post.comments_by_parent) %></li>
  <% end %>
</ul>