config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :comments, only: [:show, :create] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :votes, only: [:destroy]
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           default(""), not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs, source: :post
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in, except: [:index, :show]
  before_action :require_sub_ownership, only: [:edit, :update, :destroy]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors]=@sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
  end

  def update
    @sub = Sub.find_by(id: params[:id])
      if @sub.update_attributes(sub_params)
        redirect_to sub_url(@sub)
      else
        flash.now[:errors]=@sub.errors.full_messages
        render :edit
      end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    if @sub
      @sub.destroy
      redirect_to subs_url
    else
      flash[:errors]=@sub.errors.full_messages
      redirect_to sub_url(@sub)
    end
  end

  private

  def require_sub_ownership
    @sub = Sub.find_by(id: params[:id])
    unless current_user == @sub.moderator
      flash[:errors]=["Cannot modify someone else\'s sub!"]
      redirect_to sub_url(@sub)
    end
  end

  def sub_params
    params.require(:sub).permit(:title,:description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>

<%= render '/shared/errors' %>
<form class="" action="<%=action_url%>" method="post">
  <% if !sub.id.nil? && action_url == sub_url(sub) %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Sub Name:
    <input type="title" name="sub[title]" value="<%=sub.title%>">
  </label>
  <label>Description:
    <textarea name="sub[description]"><%=sub.description%></textarea>
  </label>
  <input type="submit" name="" value="<%=action_url == subs_url ? 'Create Sub' : 'Update Sub'%>">

</form>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render 'form', sub: @sub %>

app/views/subs/index.html.erb
<h1>Subs Index</h1>

<%= render '/shared/errors' %>
<ul>
<% @subs.each do |sub| %>
  <li><%=link_to sub.title, sub_url(sub)%></li>
<% end %>
</ul>
<%= link_to "Add New Sub", new_sub_url %>

app/views/subs/new.html.erb
<h1>Create A New Sub</h1>

<%= render 'form', sub: @sub %>

app/views/subs/show.html.erb
<h1><%=@sub.title%></h1>
<a><%=@sub.description%></a>
<br>
<% if @sub.moderator == current_user %>
  <%= link_to "Edit Sub", edit_sub_url %>
  <br>
<% end %>
<%= render '/shared/errors' %>
<br><br>

<h2>Posts</h2>
<%= link_to "Add Post", new_post_url %>
<section class="sub-posts">
<ul>
  <% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %>
  <br><%= post.content %>
  </li>
  <a class="karma">Karma: <%=post.sum_votes%></a>

  <%= link_to '<i class="fa fa-arrow-up"></i>'.html_safe, upvote_post_url(post), method: :post %>
  <%= link_to '<i class="fa fa-arrow-down"></i>'.html_safe, downvote_post_url(post), method: :post %>
  <% end %>
</ul>
</section>

<%= link_to "Back To Sub Index", subs_url %>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>