config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :comments, only: [:show, :create] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :votes, only: [:destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  include Votable
  validates :title, :author, presence: true
  validates :subs, presence: { message: 'must have at least one sub' }

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments

  def comments_by_parent
    comments_by_parent = Hash.new { |h, k| h[k]=[] }
    self.comments.each do |comment|
      comments_by_parent[comment.parent_comment] << comment
    end
    comments_by_parent
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, except: [:index, :show]
  before_action :require_post_ownership, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post
      @post.destroy
      redirect_to sub_posts_url(@post.subs)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to post_url(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids:[])
  end

  def require_post_ownership
    @post = Post.find_by(id: params[:id])
    unless current_user == @post.author
      flash[:errors]=["Cannot modify someone else\'s post!"]
      redirect_to post_url(@post)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url%>

<%= render '/shared/errors' %>
<form class="" action="<%=action_url%>" method="post">
  <% if !post.id.nil? && action_url == post_url(post) %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Post Title:
    <input type="text" name="post[title]" value="<%=@post.title%>">
  </label>
  <label>URL:
    <input type="text" name="post[url]" value="<%=@post.url%>">
  </label>
  <label>Content:
    <textarea name="post[content]"><%=@post.content%></textarea>
  </label>
  <br>
  <h3>Subs to share post in: </h3>
  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.order(:title).each do |sub| %>
    <label><%= sub.title %>
      <input
        type="checkbox"
        value="<%= sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>
  <input type="submit" name="" value="<%=action_url == posts_url ? 'Create Post' : 'Update Post'%>">
</form>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h2><%=link_to @post.title, "http://#{@post.url}"%></h2>
<a class="karma">Karma: <%=@post.sum_votes%></a>
<%= button_to "Upvote", upvote_post_url(@post) %>
<%= button_to "Downvote", downvote_post_url(@post) %>
<br>
<a><%=@post.content%></a><br>
<% if @post.author == current_user %>
  <%= link_to "Edit Post", edit_post_url %>
  <br>
<% end %>


  <h2>Comments</h2>

  <form class="" action="<%=comments_url%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="hidden" name="comment[post_id]" value="<%=@post.id%>">
    <label>Comment:
    <textarea name="comment[content]"></textarea>
    </label>
    <input type="submit" name="" value="Add Comment">
  </form>
  <br><br>

  <ul>
    <% @post.comments_by_parent[nil].each do |child| %>
      <li><%= render("comments/comment",
              comment: child,
              comments_by_parent: @post.comments_by_parent) %></li>
    <% end %>
  </ul>

  <br><br>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>