config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :comments, only: [:show, :create] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :votes, only: [:destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditclone</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <a class="logo_container" href="<%=subs_url%>">
      <img class="snoo_logo" href="<%=subs_url%>" src="/assets/snoo_logo.png">
  </a>
  <h1>Reddit Clone</h1>
    <nav>
      <% if logged_in? %>
        Hi, <%= current_user.username %>
        <%= button_to "Log Out", session_url, method: :delete %>
      <% else %>
      <ul>
        <li><%= link_to "Create Account", new_user_url %></li>
        <li><%= link_to "Sign In", new_session_url %></li>
      <% end %>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>